[package]
name = "matchain-supply-apis"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
axum = "0.8.4"
dotenvy = "0.15.7"
ethers = "2.0.14"
fs = "0.0.5"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = { version = "1", features = ["full"] }
tower = "0.5.2"
